### ISSUE TITLE
Swipe delete

### ISSUE THREAD

**Issue by TheAnsgar** [Erik0806/notify#20]
Add confirmation when deleting a notify by swiping it to the left

**Comment by Erik0806** [comment]
Do you mean a button, like when swiping to the right, or a popup?

**Comment by TheAnsgar** [comment]
A buttonVon: Erik0806 ***@***.***>Gesendet: Mittwoch, 1. März 2023, 07:45An: Erik0806/notify ***@***.***>Cc: TheAnsgar ***@***.***>; Author ***@***.***>Betreff: Re: [Erik0806/notify] Swipe delete (Issue #20)
Do you mean a button, like when swiping to the right, or a popup?
